pysat/pysatMadrigal

.coveragerc, .travis.yml, pysatMadrigal/tests/test_instruments.py, setup.cfg
The instrument tests inherited from pysat have been updated with new tests.  Adding skip notation to these until #5 is sorted out.
Also, update setup.cfg to consolidate settings, as in pysat.
=> TST: Update for latest pysat testing updates

pysatMadrigal/instruments/dmsp_ivm.py, pysatMadrigal/instruments/jro_isr.py, pysatMadrigal/instruments/methods/madrigal.py, pysatMadrigal/instruments/templates/madrigal_pandas.py
Addresses pysat/pysat#180 and pysat/pysat#486
- Updates instrument docstring standards based on v2.2 scrub.
- Includes refs and acknowlegdements for instruments
=> DOC: update docstrings

pysatMadrigal/instruments/dmsp_ivm.py, pysatMadrigal/instruments/jro_isr.py, pysatMadrigal/instruments/methods/madrigal.py, pysatMadrigal/instruments/templates/madrigal_pandas.py
Addresses pysat/pysat#473, test with pysat/pysat#556
Updates use of `sat_id` to `inst_id`.
Passing locally with the `break/inst_id` branch of pysat.  Expected to fail on Travis until pysat/pysat#556 is merged.
=> MAINT: use inst_id

pysatMadrigal/instruments/gnss_tec.py, pysatMadrigal/instruments/jro_isr.py, pysatMadrigal/instruments/methods/madrigal.py
There's too much about the GNSS_TEC instrument I fixed in the other PR for them to be reviewed separately.  Merging the PRs together.
=> Things got too complicated

.travis.yml, pysatMadrigal/instruments/methods/madrigal.py, pysatMadrigal/tests/test_general_methods.py, pysatMadrigal/tests/test_instruments.py
This PR works in conjunction with pysat/pysat#623.  Allows user and email to be passed through the instruments in test_instruments.py for Madrigal database.  Removes auto-generation of test values in the instrument methods.
Note this is expected to fail on Travis until changes at pysat are merged into develop-3.  Passes locally with the pysat test branch.
=> TST: support user / password info in unit tests

pysatMadrigal/instruments/dmsp_ivm.py, pysatMadrigal/instruments/gnss_tec.py, pysatMadrigal/instruments/jro_isr.py
Removed unused kwarg `fake_daily_files_from_monthly` from `list_files` routine in all instruments.
=> MAINT: remove unused kwarg

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md, .travis.yml, .zenodo.json, CODE_OF_CONDUCT.md, CONTRIBUTING.md, MANIFEST.in, conda_requirements.txt, pip_requirements.txt, setup.cfg
Added missing community documents, addressing #2.  Also added a .zenodo.json file, updated setup configuration and travis.yml to comply with up-to-date methods used in pysatSpaceWeather.
=> Updated community documents

CHANGELOG.md, pysatMadrigal/instruments/dmsp_ivm.py, pysatMadrigal/instruments/gnss_tec.py, pysatMadrigal/instruments/jro_isr.py, pysatMadrigal/instruments/methods/madrigal.py, pysatMadrigal/instruments/templates/madrigal_pandas.py
This addresses #5 and also improves the style of the general instrument template, which will eventually be fixed up to address #1.
To test:
```
import datetime as dt
import pysat
import pysatMadrigal as py_mad
dmsp_f13 = pysat.Instrument(inst_module=py_mad.instruments.dmsp_ivm, tag='utd', inst_id='f13')
out = dmsp_f13._list_remote_files_rtn(dmsp_f13.tag, dmsp_f13.inst_id, user="Your Name", password="your@email", start=py_mad.instruments.dmsp_ivm._test_dates[dmsp_f13.inst_id][dmsp_f13.tag], stop=py_mad.instruments.dmsp_ivm._test_dates[dmsp_f13.inst_id][dmsp_f13.tag] + dt.timedelta(days=1))
print(out)
```
Yields
```
1997-12-31    dms_ut_19971231_13.002.hdf5
1998-01-01    dms_ut_19980101_13.002.hdf5
1998-01-02    dms_ut_19980102_13.002.hdf5
dtype: object
```
=> Fixed bug in remote file listing method

pysatMadrigal/tests/test_instruments.py
Updates testing to be consistent with https://github.com/pysat/pysat/pull/637
=> ENH: Update to latest pysat standards

CHANGELOG.md, pysatMadrigal/instruments/jro_isr.py, pysatMadrigal/instruments/methods/general.py
Fixed a bug found in which newer JRO drift files have different variable names than earlier files.
```
import datetime as dt
import pysat
import pysatMadrigal
stime = dt.datetime(2020, 1, 13)
etime = dt.datetime(2020, 1, 23)
jro = pysat.Instruments(inst_module=pysatMadrigal.instruments.jro_isr, tag='drifts')
jro.download(start=stime, stop=etime)
jro.load(date=stime, end_date=etime)
pysat WARNING: unknown data variable(s) ['vipn2' 'dvipn2' 'vipe1' 'dvipe1' 'vi72' 'dvi72' 'vi82' 'dvi82'], using only: ['nwlos' 'range' 'vipn' 'dvipn' 'vipe' 'dvipe' 'vi7' 'dvi7' 'vi8' 'dvi8'
'paiwl' 'pacwl' 'pbiwl' 'pbcwl' 'pciel' 'pccel' 'pdiel' 'pdcel' 'jro10'
'jro11']
```
* Operating system: OS X Mojave
* …
=> JRO variable name update

pysatMadrigal/instruments/methods/general.py, pysatMadrigal/tests/test_methods_general.py
Partially addresses #3 by adding unit tests for the functions in the general methods sub-module.
Ran new unit tests locally
* Operating system: OS X Mojave
* Any details about your local setup that are relevant: develop branch of pysat
If this is a release PR, replace the first item of the above checklist with the
release checklist on the pysat wiki:
https://github.com/pysat/pysat/wiki/Checklist-for-Release
=> Added missing unit tests for `pysatMadrigal.instruments.methods.general`

CHANGELOG.md, pysatMadrigal/instruments/dmsp_ivm.py, pysatMadrigal/instruments/gnss_tec.py, pysatMadrigal/instruments/jro_isr.py
When looking at coveralls, I discovered that the clean routines contained logic for 'none'.  Since clean is not called with this input, I decided to remove it.  I also:
- moved a no-cleaning warning in JRO ISR to preprocess so that it will be accessible
- Updated the clean docstrings
```
import pysat
import pysatMadrigal as py_mad
jro = pysat.Instrument(inst_module=py_mad.instruments.jro_isr, tag='drifts', clean_level='none')
jro.load(2014, 20)
pysat WARNING: unknown data variable(s) ['vipn' 'dvipn' 'vipe' 'dvipe' 'vi7' 'dvi7' 'vi8' 'dvi8'], using only: ['nwlos' 'range' 'vipn2' 'dvipn2' 'vipe1' 'dvipe1' 'vi72' 'dvi72' 'vi82'
'dvi82' 'paiwl' 'pacwl' 'pbiwl' 'pbcwl' 'pciel' 'pccel' 'pdiel' …
```
=> Updated cleaning methods

pysatMadrigal/instruments/methods/general.py, pysatMadrigal/tests/test_instruments.py, pysatMadrigal/tests/test_methods_general.py
Found a bug when running data validation that revealed meta data available in the netCDF4 files was not being loaded for the coordinates.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-0f94a05e9ffd> in <module>
----> 1 (pairs, pairs_meta, inst_dat, mod_dat, inst_loc) = sami3_val.pair_sami3_inst(stime, etime, inst_name, mod_prefix,
2                                     user=user, password=password,
3                                     skip_download=skip_download,
4                                     mod_dir=mod_dir, data_dir=data_dir,
5                                     data_type=data_type, comp_clean=comp_clean) …
```
=> Meta load netcdf bug

CHANGELOG.md, pysatMadrigal/instruments/gnss_tec.py, pysatMadrigal/instruments/methods/general.py, pysatMadrigal/tests/test_methods_general.py
Addresses #70 
Fixes use of `remote_file_list` for GNSS TEC `vtec`
- Added unit tests for new function errors
- Ran unit tests that originally identified `remote_file_list` issue. Works now.
* Operating system: MacOS
* Any details about your local setup that are relevant
If this is a release PR, replace the first item of the above checklist with the
release checklist on the pysat wiki:
https://github.com/pysat/pysat/wiki/Checklist-for-Release
=> Remote list break fix

CHANGELOG.md, README.md, pysatMadrigal/tests/test_instruments.py, pysatMadrigal/tests/test_methods_general.py, pysatMadrigal/tests/test_methods_gnss.py, pysatMadrigal/tests/test_methods_jro.py, pysatMadrigal/tests/test_utils_coords.py, setup.cfg
Addresses pysat/pysat#1053
Updates test syntax to be compatible with changes in pytest (`setup_method`, `teardown_method`) and pysat (streamline the instrument tests).
Github Actions
If this is a release PR, replace the first item of the above checklist with the
release checklist on the pysat wiki:
https://github.com/pysat/pysat/wiki/Checklist-for-Release
=> MAINT: syntax for pytest and pysat

.github/workflows/pip_rc_install.yml, .github/workflows/pysat_rc.yml, CHANGELOG.md, pysatMadrigal/__init__.py, test_requirements.txt
Addresses https://github.com/pysat/pysat/issues/1051. Because pip now builds a wheel locally (by default), it tries to download `setuptools` from test pypi, which isn't there.
Updates RC install options for work with pysat release candidates on test.pypi
Adds a new workflow to test install of the pysatMadrigal RC from test.pypi
Running manual tests for the RC workflows.
* Operating system: GitHUb Actions
* https://github.com/pysat/pysatMadrigal/actions/workflows/pysat_rc.yml
* https://github.com/pysat/pysatMadrigal/actions/workflows/pip_rc_install.yml -- not yet in main, needs to be temporarily set to push
If this is a release PR, replace the first item of the …
=> MAINT: GA updates

CHANGELOG.md, docs/supported_instruments.rst, pysatMadrigal/instruments/__init__.py, pysatMadrigal/instruments/dmsp_ssj.py, pysatMadrigal/instruments/madrigal_pandas.py, pysatMadrigal/instruments/methods/dmsp.py, pysatMadrigal/instruments/methods/general.py, setup.cfg, test_requirements.txt
Added an instrument for the DMSP SSJ auroral boundary index data.  This data is stored in yearly files, and requires an update to pysat to work correctly.  It also revealed a local bug in the general download function.
- This change requires a documentation update
```
import datetime as dt
import pysat
import pysatMadrigal as pymad
stime = dt.datetime(2014, 3, 26)
ssj = pysat.Instrument(inst_module=pymad.instruments.dmsp_ssj, tag='abi')
ssj.download(start=stime)
ssj.load(date=stime)
ssj.data
```
Yields
```
year  month   day  ...  eqb_prb_kp  sat_id   epowq
2014-03-26 00:06:45  2014.0    3.0  26.0  ...       0.911 …
```
=> ENH: Added a DMSP SSJ instrument

CHANGELOG.md, docs/supported_instruments.rst, pysatMadrigal/instruments/__init__.py, pysatMadrigal/instruments/dmsp_ssj.py, pysatMadrigal/instruments/madrigal_pandas.py, pysatMadrigal/instruments/methods/dmsp.py, pysatMadrigal/instruments/methods/general.py, requirements.txt, setup.cfg, test_requirements.txt
Removes logic needed to get around pysat behaviour that doesn't recognize the default values of start/stop set outside of the pysat.Instrument for remote_file_list functions.  Requires https://github.com/pysat/pysat/pull/1083 to work.
```
import pysat
dmsp = pysat.Instrument('dmsp', 'ivm', inst_id='f15')
dmsp.remote_file_list(user='your name', password='your email')
```
I added a RuntimeError to `pysatMadrigal.instruments.general.list_remote_files` when testing to ensure the start/stop times matched the defaults when using this call.
* Operating system: OS X Big Sur
* Any details about your local setup that are relevant: pysat …
=> Update pysat remote file list

CHANGELOG.md, docs/supported_instruments.rst, pysatMadrigal/instruments/__init__.py, pysatMadrigal/instruments/madrigal_dst.py, pysatMadrigal/instruments/madrigal_geoind.py, pysatMadrigal/instruments/madrigal_pandas.py, pysatMadrigal/instruments/ngdc_ae.py, pysatMadrigal/instruments/omni2_imf.py
Addresses #91 by creating instrument sub-modules for the remaining madrigal index files.
- Breaking change (fix or feature that would cause existing functionality
to not work as expected)
- This change requires a documentation update
```
import pysat
import pysatMadrigal as pymad
dst = pysat.Instrument(inst_module=pymad.instruments.madrigal_dst, user='User Name', password='your email')
dst.download(start=pymad.instruments.madrigal_dst.madrigal_start)
dst.load(1981, 1)
```
* Operating system: OS X Big Sur
* Any details about your local setup that are relevant
If this is a release PR, …
=> Move Madrigal index Instruments to their own sub-modules

.github/workflows/main.yml, .github/workflows/pysat_rc.yml, CHANGELOG.md, docs/methods.rst, pyproject.toml, pysatMadrigal/instruments/dmsp_ivm.py, pysatMadrigal/instruments/gnss_tec.py, pysatMadrigal/instruments/methods/general.py, pysatMadrigal/instruments/methods/gnss.py, pysatMadrigal/tests/test_instruments.py, pysatMadrigal/tests/test_methods_general.py, pysatMadrigal/tests/test_methods_gnss.py, test_requirements.txt
Addresses #12 by adding the 'los' tag to the TEC instrument.  Also refactored the general load function to facilitate the new targeted load function needed for the LoS TEC.
- This change requires a documentation update
```
import datetime as dt
import pysat
import pysatMadrigal as pymad
stec = pysat.Instrument(inst_module=pymad.instruments.gnss_tec, tag='stec')
stec.download(dt.datetime(2023, 1, 1), user="your name", password='your email')
sites = pymad.instruments.methods.gnss.get_los_receiver_sites(stec.files.files[0])
stec.load(2023, 1, los_method='site', los_value=sites[-1])
print(stec.variables)
```
yeilds:
```
['time', 'gps_site', 'sat_id', 'kindat', 'kinst', …
```
=> Added LoS TEC tag to the GNSS TEC Instrument

ACKNOWLEDGEMENTS.md, CHANGELOG.md, README.md, docs/acknowledgements.rst, docs/index.rst, pyproject.toml, pysatMadrigal/instruments/dmsp_ivm.py, pysatMadrigal/instruments/dmsp_ssj.py, pysatMadrigal/instruments/gnss_tec.py, pysatMadrigal/instruments/jro_isr.py, pysatMadrigal/instruments/madrigal_dst.py, pysatMadrigal/instruments/madrigal_geoind.py, pysatMadrigal/instruments/methods/dmsp.py, pysatMadrigal/instruments/methods/general.py, pysatMadrigal/instruments/methods/gnss.py, pysatMadrigal/instruments/methods/jro.py, pysatMadrigal/instruments/ngdc_ae.py, pysatMadrigal/instruments/omni2_imf.py, pysatMadrigal/tests/test_instruments.py, pysatMadrigal/tests/test_methods_dmsp.py, pysatMadrigal/tests/test_methods_general.py, pysatMadrigal/tests/test_methods_gnss.py, pysatMadrigal/tests/test_methods_jro.py, pysatMadrigal/tests/test_utils_coords.py, pysatMadrigal/utils/coords.py, setup.cfg
Updates acknowledgements and headers to include the NRL pub release
- This change requires a documentation update
unit tests
* Operating system: OS X Big Sur
* Any details about your local setup that are relevant
If this is a release PR, replace the first item of the above checklist with the
release checklist on the pysat wiki:
https://github.com/pysat/pysat/wiki/Checklist-for-Release
=> NRL pub release
